### ISSUE TITLE
Unable to identify base64

### ISSUE THREAD

**Issue by thelicato** [swanandx/lemmeknow#18]
Hi, I'm trying ``lemmeknow`` and I gotta say that it works quite well with links (e.g. YouTube channels, wallets and so on), but it misses to detect the easiest things. For example it is unable to recognize a **base64** encoded text.

Nice work though.

**Comment by swanandx** [comment]
Lemmeknow doesn't identify what encoding was used! 

I made a video on how it works - [YouTube](https://youtu.be/n92YrzELBJU)

If you want something that automatically decrypts something, check out [Ares](https://github.com/bee-san/Ares).

PS: Ares uses lemmeknow to check if it got any plaintext after decryption :)

**Comment by wookayin** [comment]
Then it does not sound like identify "anything".

**Comment by swanandx** [comment]
Well certainly it can't identify what _encryption / encoding_ was used on something. If you want to do it, check out the [project Ares](https://github.com/bee-san/Ares) which uses lemmeknow. PS: I'm one of the contributors in Ares haha
