### ISSUE TITLE
Allow querying the online lemmeknow by URL

### ISSUE THREAD

**Issue by DrRuhe** [swanandx/lemmeknow#20]
When opening the lemmeknow webpage with a URL such as this:
`https://swanandx.github.io/lemmeknow-frontend/?q=search+term`
It should use this as input and try to figure out what the search term could be. 

## Why?
Browser Search engines.

With this feature you could register lemmeknow as a search engine for your browser. You could (for example) use the alias `lmk` to search lemmeknow. 

Then typing `lmk dQw4w9WgXcQ` would lead you to find out what the ID stands for.

**Comment by swanandx** [comment]
Thanks for the suggestion, but this issue should be at lemmeknow-frontend. Can you please move it there?

https://github.com/swanandx/lemmeknow-frontend
