### ISSUE TITLE
Use bytes instead of strings, ditch fancy_regex for regex crate

### ISSUE THREAD

**Issue by SkeletalDemise** [swanandx/lemmeknow#8]
Currently lemmeknow uses the `fancy_regex` crate for matching regex. The problem is that it doesn't support bytes. The `regex` crate, however does: https://docs.rs/regex/1.0.0/regex/bytes/index.html

If there is no reason to use `fancy_regex` then we should switch. Both pyWhat and lemmeknow only support ASCII strings. We need to support UTF-8, UTF-16, etc. and bytes.

See this equivalent pyWhat issue: https://github.com/bee-san/pyWhat/issues/34

**Comment by swanandx** [comment]
`regex` crate does not support look-around, so if we try to use it, we are not able to compile the regular expressions from `regexs.json` file.

![image](https://user-images.githubusercontent.com/73115739/180393203-68278d55-0686-42f9-a545-d0a12aa2c3cf.png)

That is why we use `fancy-regex`.

`lemmeknow` do support UTF-8 as the Strings are UTF-8 in Rust. ( and we also tested with UTF-16 right? ).
